// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tenminutes;

import com.tenminutes.Timer;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect TimerDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TimerDataOnDemand: @Component;
    
    private Random TimerDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Timer> TimerDataOnDemand.data;
    
    public Timer TimerDataOnDemand.getNewTransientTimer(int index) {
        com.tenminutes.Timer obj = new com.tenminutes.Timer();
        obj.setMessage("message_" + index);
        return obj;
    }
    
    public Timer TimerDataOnDemand.getSpecificTimer(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Timer obj = data.get(index);
        return Timer.findTimer(obj.getId());
    }
    
    public Timer TimerDataOnDemand.getRandomTimer() {
        init();
        Timer obj = data.get(rnd.nextInt(data.size()));
        return Timer.findTimer(obj.getId());
    }
    
    public boolean TimerDataOnDemand.modifyTimer(Timer obj) {
        return false;
    }
    
    public void TimerDataOnDemand.init() {
        data = com.tenminutes.Timer.findTimerEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Timer' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.tenminutes.Timer>();
        for (int i = 0; i < 10; i++) {
            com.tenminutes.Timer obj = getNewTransientTimer(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
