
package org.suggs.sandbox.jaxws.simple.client.bindings;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HelloWorldService", targetNamespace = "http://test.suggs.org.uk", wsdlLocation = "file:/home/suggitpe/git-snapshots/java-web/sandbox/sandbox-webservices/jax-ws-simple/client/src/main/resources/wsdl/HelloWorldService.wsdl")
public class HelloWorldService
    extends Service
{

    private final static URL HELLOWORLDSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.suggs.sandbox.jaxws.simple.client.bindings.HelloWorldService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.suggs.sandbox.jaxws.simple.client.bindings.HelloWorldService.class.getResource(".");
            url = new URL(baseUrl, "file:/home/suggitpe/git-snapshots/java-web/sandbox/sandbox-webservices/jax-ws-simple/client/src/main/resources/wsdl/HelloWorldService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/suggitpe/git-snapshots/java-web/sandbox/sandbox-webservices/jax-ws-simple/client/src/main/resources/wsdl/HelloWorldService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HELLOWORLDSERVICE_WSDL_LOCATION = url;
    }

    public HelloWorldService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldService() {
        super(HELLOWORLDSERVICE_WSDL_LOCATION, new QName("http://test.suggs.org.uk", "HelloWorldService"));
    }

    /**
     * 
     * @return
     *     returns HelloWorld
     */
    @WebEndpoint(name = "HelloWorldPort")
    public HelloWorld getHelloWorldPort() {
        return super.getPort(new QName("http://test.suggs.org.uk", "HelloWorldPort"), HelloWorld.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorld
     */
    @WebEndpoint(name = "HelloWorldPort")
    public HelloWorld getHelloWorldPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://test.suggs.org.uk", "HelloWorldPort"), HelloWorld.class, features);
    }

}
